import { CatalogService } from "./types";

export const SERVICE_CATALOG: CatalogService[] = [
  // Streaming Video
  {
    name: "Netflix",
    category: "streaming",
    color: "#E50914",
    emailDomains: ["netflix.com"],
    emailSubjects: ["Your Netflix membership", "Netflix receipt", "Resumen de tu suscripción de Netflix"],
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    defaultPrice: 15.49,
    defaultCurrency: "USD",
  },
  {
    name: "HBO Max",
    category: "streaming",
    color: "#5822B4",
    emailDomains: ["hbomax.com", "max.com", "warnermediaprivacy.com"],
    emailSubjects: ["HBO Max", "Max subscription", "Your Max receipt"],
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/HBO_Max_Logo.svg",
    defaultPrice: 15.99,
    defaultCurrency: "USD",
  },
  {
    name: "Disney+",
    category: "streaming",
    color: "#113CCF",
    emailDomains: ["disneyplus.com", "disneystreaming.com"],
    emailSubjects: ["Disney+", "Your Disney+ subscription"],
    defaultPrice: 13.99,
    defaultCurrency: "USD",
  },
  {
    name: "Amazon Prime Video",
    category: "streaming",
    color: "#00A8E1",
    emailDomains: ["amazon.com", "primevideo.com"],
    emailSubjects: ["Amazon Prime", "Prime Video"],
    defaultPrice: 14.99,
    defaultCurrency: "USD",
  },
  {
    name: "Paramount+",
    category: "streaming",
    color: "#0064FF",
    emailDomains: ["paramountplus.com", "cbsinteractive.com"],
    emailSubjects: ["Paramount+"],
    defaultPrice: 5.99,
    defaultCurrency: "USD",
  },
  {
    name: "Apple TV+",
    category: "streaming",
    color: "#555555",
    emailDomains: ["apple.com"],
    emailSubjects: ["Apple TV+", "Apple One"],
    defaultPrice: 9.99,
    defaultCurrency: "USD",
  },
  {
    name: "Crunchyroll",
    category: "streaming",
    color: "#F47521",
    emailDomains: ["crunchyroll.com"],
    emailSubjects: ["Crunchyroll"],
    defaultPrice: 7.99,
    defaultCurrency: "USD",
  },
  // Music
  {
    name: "Spotify",
    category: "music",
    color: "#1DB954",
    emailDomains: ["spotify.com"],
    emailSubjects: ["Spotify", "Your Spotify receipt", "Tu recibo de Spotify"],
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg",
    defaultPrice: 10.99,
    defaultCurrency: "USD",
  },
  {
    name: "Apple Music",
    category: "music",
    color: "#FC3C44",
    emailDomains: ["apple.com"],
    emailSubjects: ["Apple Music"],
    defaultPrice: 10.99,
    defaultCurrency: "USD",
  },
  {
    name: "YouTube Music",
    category: "music",
    color: "#FF0000",
    emailDomains: ["google.com", "youtube.com"],
    emailSubjects: ["YouTube Music", "YouTube Premium"],
    defaultPrice: 10.99,
    defaultCurrency: "USD",
  },
  {
    name: "Tidal",
    category: "music",
    color: "#000000",
    emailDomains: ["tidal.com"],
    emailSubjects: ["Tidal"],
    defaultPrice: 10.99,
    defaultCurrency: "USD",
  },
  // AI & Productivity
  {
    name: "ChatGPT Plus",
    category: "productivity",
    color: "#10A37F",
    emailDomains: ["openai.com"],
    emailSubjects: ["OpenAI", "ChatGPT Plus", "Your ChatGPT subscription"],
    defaultPrice: 20,
    defaultCurrency: "USD",
  },
  {
    name: "Claude Pro",
    category: "productivity",
    color: "#CC785C",
    emailDomains: ["anthropic.com"],
    emailSubjects: ["Anthropic", "Claude Pro"],
    defaultPrice: 20,
    defaultCurrency: "USD",
  },
  {
    name: "GitHub Copilot",
    category: "productivity",
    color: "#24292E",
    emailDomains: ["github.com"],
    emailSubjects: ["GitHub Copilot", "Copilot subscription"],
    defaultPrice: 10,
    defaultCurrency: "USD",
  },
  {
    name: "Notion",
    category: "productivity",
    color: "#000000",
    emailDomains: ["notion.so"],
    emailSubjects: ["Notion"],
    defaultPrice: 16,
    defaultCurrency: "USD",
  },
  {
    name: "Figma",
    category: "productivity",
    color: "#F24E1E",
    emailDomains: ["figma.com"],
    emailSubjects: ["Figma"],
    defaultPrice: 15,
    defaultCurrency: "USD",
  },
  {
    name: "Adobe Creative Cloud",
    category: "productivity",
    color: "#FF0000",
    emailDomains: ["adobe.com"],
    emailSubjects: ["Adobe", "Creative Cloud"],
    defaultPrice: 54.99,
    defaultCurrency: "USD",
  },
  {
    name: "Microsoft 365",
    category: "productivity",
    color: "#D83B01",
    emailDomains: ["microsoft.com"],
    emailSubjects: ["Microsoft 365", "Microsoft 365 subscription"],
    defaultPrice: 9.99,
    defaultCurrency: "USD",
  },
  {
    name: "Dropbox",
    category: "cloud",
    color: "#0061FF",
    emailDomains: ["dropbox.com"],
    emailSubjects: ["Dropbox"],
    defaultPrice: 11.99,
    defaultCurrency: "USD",
  },
  {
    name: "Google One",
    category: "cloud",
    color: "#4285F4",
    emailDomains: ["google.com"],
    emailSubjects: ["Google One", "Google Storage"],
    defaultPrice: 2.99,
    defaultCurrency: "USD",
  },
  {
    name: "iCloud+",
    category: "cloud",
    color: "#147EFB",
    emailDomains: ["apple.com"],
    emailSubjects: ["iCloud+", "iCloud storage"],
    defaultPrice: 2.99,
    defaultCurrency: "USD",
  },
  // Gaming
  {
    name: "Xbox Game Pass",
    category: "gaming",
    color: "#107C10",
    emailDomains: ["microsoft.com", "xbox.com"],
    emailSubjects: ["Xbox Game Pass", "Game Pass"],
    defaultPrice: 14.99,
    defaultCurrency: "USD",
  },
  {
    name: "PlayStation Plus",
    category: "gaming",
    color: "#003087",
    emailDomains: ["playstation.com", "sony.com"],
    emailSubjects: ["PlayStation Plus", "PS Plus"],
    defaultPrice: 14.99,
    defaultCurrency: "USD",
  },
  {
    name: "Nintendo Switch Online",
    category: "gaming",
    color: "#E4000F",
    emailDomains: ["nintendo.com"],
    emailSubjects: ["Nintendo Switch Online"],
    defaultPrice: 3.99,
    defaultCurrency: "USD",
  },
  {
    name: "EA Play",
    category: "gaming",
    color: "#FF4747",
    emailDomains: ["ea.com"],
    emailSubjects: ["EA Play"],
    defaultPrice: 4.99,
    defaultCurrency: "USD",
  },
  // News & Reading
  {
    name: "The New York Times",
    category: "news",
    color: "#000000",
    emailDomains: ["nytimes.com"],
    emailSubjects: ["New York Times"],
    defaultPrice: 17,
    defaultCurrency: "USD",
  },
  {
    name: "Medium",
    category: "news",
    color: "#000000",
    emailDomains: ["medium.com"],
    emailSubjects: ["Medium membership"],
    defaultPrice: 5,
    defaultCurrency: "USD",
  },
  {
    name: "Kindle Unlimited",
    category: "news",
    color: "#FF9900",
    emailDomains: ["amazon.com"],
    emailSubjects: ["Kindle Unlimited"],
    defaultPrice: 9.99,
    defaultCurrency: "USD",
  },
  // Fitness
  {
    name: "Strava",
    category: "fitness",
    color: "#FC4C02",
    emailDomains: ["strava.com"],
    emailSubjects: ["Strava"],
    defaultPrice: 7.99,
    defaultCurrency: "USD",
  },
  {
    name: "Peloton",
    category: "fitness",
    color: "#CC0000",
    emailDomains: ["onepeloton.com"],
    emailSubjects: ["Peloton"],
    defaultPrice: 12.99,
    defaultCurrency: "USD",
  },
  // Finance
  {
    name: "Duolingo Plus",
    category: "education",
    color: "#58CC02",
    emailDomains: ["duolingo.com"],
    emailSubjects: ["Duolingo Plus", "Duolingo Super"],
    defaultPrice: 6.99,
    defaultCurrency: "USD",
  },
  {
    name: "Coursera Plus",
    category: "education",
    color: "#0056D2",
    emailDomains: ["coursera.org"],
    emailSubjects: ["Coursera Plus"],
    defaultPrice: 59,
    defaultCurrency: "USD",
  },
  {
    name: "Canva Pro",
    category: "productivity",
    color: "#00C4CC",
    emailDomains: ["canva.com"],
    emailSubjects: ["Canva Pro"],
    defaultPrice: 12.99,
    defaultCurrency: "USD",
  },
  {
    name: "Slack",
    category: "productivity",
    color: "#4A154B",
    emailDomains: ["slack.com"],
    emailSubjects: ["Slack Pro"],
    defaultPrice: 7.25,
    defaultCurrency: "USD",
  },
  {
    name: "Zoom",
    category: "productivity",
    color: "#2D8CFF",
    emailDomains: ["zoom.us"],
    emailSubjects: ["Zoom Pro"],
    defaultPrice: 14.99,
    defaultCurrency: "USD",
  },
  {
    name: "1Password",
    category: "productivity",
    color: "#1A8CFF",
    emailDomains: ["1password.com"],
    emailSubjects: ["1Password"],
    defaultPrice: 2.99,
    defaultCurrency: "USD",
  },
  {
    name: "NordVPN",
    category: "other",
    color: "#4687FF",
    emailDomains: ["nordvpn.com"],
    emailSubjects: ["NordVPN"],
    defaultPrice: 3.99,
    defaultCurrency: "USD",
  },
  {
    name: "ExpressVPN",
    category: "other",
    color: "#DA3940",
    emailDomains: ["expressvpn.com"],
    emailSubjects: ["ExpressVPN"],
    defaultPrice: 8.32,
    defaultCurrency: "USD",
  },
  {
    name: "Twitch Turbo",
    category: "streaming",
    color: "#9146FF",
    emailDomains: ["twitch.tv"],
    emailSubjects: ["Twitch Turbo"],
    defaultPrice: 8.99,
    defaultCurrency: "USD",
  },
  {
    name: "YouTube Premium",
    category: "streaming",
    color: "#FF0000",
    emailDomains: ["google.com", "youtube.com"],
    emailSubjects: ["YouTube Premium"],
    defaultPrice: 13.99,
    defaultCurrency: "USD",
  },
  // App Stores (aggregators — detect individual apps from receipts)
  {
    name: "Apple App Store",
    category: "other",
    color: "#555555",
    emailDomains: ["email.apple.com"],
    emailSubjects: ["Your receipt from Apple", "Recibo de Apple", "Tu recibo de Apple"],
    isAggregator: true,
  },
  {
    name: "Google Play Store",
    category: "other",
    color: "#4285F4",
    emailDomains: ["play.google.com"],
    emailSubjects: ["receipt from Google Play", "Your Google Play Order Receipt", "Tu recibo de Google Play"],
    isAggregator: true,
  },
  // Payment platforms
  {
    name: "PayPal",
    category: "finance",
    color: "#003087",
    emailDomains: ["paypal.com"],
    emailSubjects: ["subscription", "billing agreement", "pago automático", "automatic payment"],
    defaultCurrency: "USD",
  },
  {
    name: "Mercado Pago",
    category: "finance",
    color: "#00BCFF",
    emailDomains: ["mercadopago.com"],
    emailSubjects: ["suscripción", "cobro automático", "débito automático"],
    defaultCurrency: "ARS",
  },
  // More services
  {
    name: "Headspace",
    category: "fitness",
    color: "#F47D31",
    emailDomains: ["headspace.com"],
    emailSubjects: ["Headspace"],
    defaultPrice: 12.99,
    defaultCurrency: "USD",
  },
  {
    name: "Calm",
    category: "fitness",
    color: "#4A90D9",
    emailDomains: ["calm.com"],
    emailSubjects: ["Calm Premium"],
    defaultPrice: 14.99,
    defaultCurrency: "USD",
  },
  {
    name: "Audible",
    category: "news",
    color: "#F8991D",
    emailDomains: ["audible.com"],
    emailSubjects: ["Audible"],
    defaultPrice: 14.95,
    defaultCurrency: "USD",
  },
  {
    name: "LinkedIn Premium",
    category: "productivity",
    color: "#0A66C2",
    emailDomains: ["linkedin.com"],
    emailSubjects: ["LinkedIn Premium"],
    defaultPrice: 39.99,
    defaultCurrency: "USD",
  },
  {
    name: "Grammarly",
    category: "productivity",
    color: "#15C39A",
    emailDomains: ["grammarly.com"],
    emailSubjects: ["Grammarly Premium"],
    defaultPrice: 12,
    defaultCurrency: "USD",
  },
  {
    name: "Dashlane",
    category: "productivity",
    color: "#006FFF",
    emailDomains: ["dashlane.com"],
    emailSubjects: ["Dashlane"],
    defaultPrice: 4.99,
    defaultCurrency: "USD",
  },
  {
    name: "Lastpass",
    category: "productivity",
    color: "#CC0000",
    emailDomains: ["lastpass.com"],
    emailSubjects: ["LastPass"],
    defaultPrice: 3,
    defaultCurrency: "USD",
  },
  {
    name: "Evernote",
    category: "productivity",
    color: "#00A82D",
    emailDomains: ["evernote.com"],
    emailSubjects: ["Evernote"],
    defaultPrice: 14.99,
    defaultCurrency: "USD",
  },
  {
    name: "Todoist",
    category: "productivity",
    color: "#DB4035",
    emailDomains: ["todoist.com"],
    emailSubjects: ["Todoist Pro"],
    defaultPrice: 4,
    defaultCurrency: "USD",
  },
  {
    name: "Plex Pass",
    category: "streaming",
    color: "#E5A00D",
    emailDomains: ["plex.tv"],
    emailSubjects: ["Plex Pass"],
    defaultPrice: 4.99,
    defaultCurrency: "USD",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  streaming: "Streaming",
  music: "Música",
  productivity: "Productividad",
  gaming: "Gaming",
  cloud: "Almacenamiento",
  news: "Noticias & Lectura",
  fitness: "Fitness",
  education: "Educación",
  finance: "Finanzas",
  other: "Otros",
};

export const CATEGORY_COLORS: Record<string, string> = {
  streaming: "#E50914",
  music: "#1DB954",
  productivity: "#10A37F",
  gaming: "#107C10",
  cloud: "#4285F4",
  news: "#333333",
  fitness: "#FC4C02",
  education: "#0056D2",
  finance: "#00AA55",
  other: "#888888",
};

export const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  CLP: "$",
  EUR: "€",
  MXN: "$",
  ARS: "$",
  COP: "$",
};
